name: NovoWorkflow

on:
  push:
    branches: [develop]
  pull_request:
    branches: [release]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .Net Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100

    - name: Install dependencies
      run: dotnet restore
      working-directory: ./src

    - name: dotnet build
      run: |
        dotnet build --configuration Release
      working-directory: ./src
      
