name: pipeline

on:
  push:

  
jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - run: mvn test  
    
    - name: Generate JaCoCo Badge
      id: jacoco
      uses: cicirello/jacoco-badge-generator@v2.0.1
    - name: Log coverage percentage
      run: |
        echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
        echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"    
    
    - name: Upload JaCoCo coverage report
      uses: actions/upload-artifact@v2
      with:
        name: jacoco-report
        path: target/site/jacoco/
        
  build:
    runs-on: ubuntu-latest
    needs: unit-test
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - run: mvn -B package -DskipTests --file pom.xml 
        
  code-analisys:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11    
    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
        
    - name: Build and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Devops-Fiap
               
  publish:
    runs-on: ubuntu-latest
    needs: build #code-analisys
    steps:
    - name: Upload JAR
        #This uploads artifacts from your workflow allowing you to share data between jobs and store data once a workflow is complete.
      uses: actions/upload-artifact@v2
      with:
        #Set artifact name
        name: artifact
        #From this path
        path: target
        
    #permissions:
    #  contents: read
    #  packages: write
    #steps:
    #  - uses: actions/checkout@v3
    #  - uses: actions/setup-java@v3
    #    with:
    #      java-version: '11'
    #      distribution: 'adopt'
    #      package: '*.jar'
    #  - name: Publish package
    #    run: mvn --batch-mode deploy
    #    env:
    #      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
          
  deploy-STG:
    runs-on: ubuntu-latest
    environment:
      name: stg
    needs: publish
    
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Deploy 
        shell: bash
        run: |
          echo "Deploy STG"
          
    
  deploy-Pre:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/release'
    environment:
      name: pre
    needs: publish

    steps:
      - name: Deploy 
        shell: bash
        run: |
          echo "Deploy PRE"
          
  deploy-Prod:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'
    environment:
      name: prod
    needs: publish

    steps:
      - name: Deploy 
        shell: bash
        run: |
          echo "Deploy PROD"       
          
  deploy-aws:
    #Depends on build's job
    needs: publish  
    name: Deploy-aws
    #Run on Ubuntu using the latest version
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Download JAR
        #Download the artifact which was uploaded in the build's job
        uses: actions/download-artifact@v2
        with:
          name: artifact
      #Deploy the artifact (JAR) into AWS Beanstalk
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v13
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
          use_existing_version_if_available: false
          application_name: spring-boot-deploy
          environment_name: Springbootdeploy-env
          version_label: ${{github.SHA}}
          region: us-east-1
          deployment_package: demo-0.0.2.6-SNAPSHOT-SNAPSHOT.jar          
